import {
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  CircleParking,
  Cloud,
  Coffee,
  CreditCard,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  HeartPulse,
  Home,
  Hotel,
  Landmark,
  Laptop,
  Leaf,
  type LucideIcon,
  Mountain,
  Music,
  Newspaper,
  Palette,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pizza,
  Plane,
  Puzzle,
  Receipt,
  Scale,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Sparkles,
  Smartphone,
  Stethoscope,
  Ticket,
  TrainFront,
  TrendingUp,
  Trophy,
  Truck,
  Umbrella,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Zap,
} from "lucide-react";

// Categories store an icon key (this list) rather than free emoji text --
// SVGs render crisp at any size and inherit a color, so the same icon can
// be tinted to match the category's color instead of carrying a fixed
// platform-dependent emoji color.
export const CATEGORY_ICONS = [
  { key: "shopping-cart", label: "Groceries", Icon: ShoppingCart },
  { key: "shopping-bag", label: "Shopping", Icon: ShoppingBag },
  { key: "utensils", label: "Dining", Icon: UtensilsCrossed },
  { key: "pizza", label: "Takeout", Icon: Pizza },
  { key: "coffee", label: "Coffee", Icon: Coffee },
  { key: "wine", label: "Alcohol", Icon: Wine },
  { key: "car", label: "Transport", Icon: Car },
  { key: "fuel", label: "Fuel", Icon: Fuel },
  { key: "bus", label: "Public transit", Icon: Bus },
  { key: "train", label: "Train", Icon: TrainFront },
  { key: "bike", label: "Cycling", Icon: Bike },
  { key: "parking", label: "Parking", Icon: CircleParking },
  { key: "home", label: "Housing", Icon: Home },
  { key: "building", label: "Rent/Mortgage", Icon: Building2 },
  { key: "hammer", label: "Home repair", Icon: Hammer },
  { key: "sofa", label: "Furniture", Icon: Sofa },
  { key: "zap", label: "Electricity", Icon: Zap },
  { key: "flame", label: "Gas", Icon: Flame },
  { key: "droplet", label: "Water", Icon: Droplet },
  { key: "wifi", label: "Internet", Icon: Wifi },
  { key: "smartphone", label: "Phone", Icon: Smartphone },
  { key: "laptop", label: "Electronics", Icon: Laptop },
  { key: "cloud", label: "Software", Icon: Cloud },
  { key: "film", label: "Entertainment", Icon: Film },
  { key: "gamepad", label: "Gaming", Icon: Gamepad2 },
  { key: "music", label: "Music", Icon: Music },
  { key: "ticket", label: "Events", Icon: Ticket },
  { key: "party-popper", label: "Celebrations", Icon: PartyPopper },
  { key: "puzzle", label: "Hobbies", Icon: Puzzle },
  { key: "palette", label: "Art", Icon: Palette },
  { key: "camera", label: "Photography", Icon: Camera },
  { key: "book-open", label: "Books", Icon: BookOpen },
  { key: "newspaper", label: "Subscriptions", Icon: Newspaper },
  { key: "heart-pulse", label: "Health", Icon: HeartPulse },
  { key: "stethoscope", label: "Medical", Icon: Stethoscope },
  { key: "dumbbell", label: "Fitness", Icon: Dumbbell },
  { key: "scissors", label: "Personal care", Icon: Scissors },
  { key: "graduation-cap", label: "Education", Icon: GraduationCap },
  { key: "plane", label: "Travel", Icon: Plane },
  { key: "hotel", label: "Lodging", Icon: Hotel },
  { key: "mountain", label: "Outdoors", Icon: Mountain },
  { key: "leaf", label: "Garden", Icon: Leaf },
  { key: "gift", label: "Gifts", Icon: Gift },
  { key: "baby", label: "Kids", Icon: Baby },
  { key: "paw-print", label: "Pets", Icon: PawPrint },
  { key: "shirt", label: "Clothing", Icon: Shirt },
  { key: "trophy", label: "Sports", Icon: Trophy },
  { key: "hand-heart", label: "Charity", Icon: HandHeart },
  { key: "scale", label: "Legal", Icon: Scale },
  { key: "umbrella", label: "Insurance", Icon: Umbrella },
  { key: "truck", label: "Moving", Icon: Truck },
  { key: "wallet", label: "Wallet", Icon: Wallet },
  { key: "piggy-bank", label: "Savings", Icon: PiggyBank },
  { key: "landmark", label: "Bank", Icon: Landmark },
  { key: "receipt", label: "Bills", Icon: Receipt },
  { key: "credit-card", label: "Fees", Icon: CreditCard },
  { key: "briefcase", label: "Work", Icon: Briefcase },
  { key: "trending-up", label: "Income", Icon: TrendingUp },
  { key: "sparkles", label: "Other", Icon: Sparkles },
] as const satisfies { key: string; label: string; Icon: LucideIcon }[];

const iconByKey = new Map<string, LucideIcon>(
  CATEGORY_ICONS.map((entry) => [entry.key, entry.Icon]),
);

export function categoryIconComponent(icon: string | null | undefined): LucideIcon | null {
  if (!icon) return null;
  return iconByKey.get(icon) ?? null;
}
